import re

shipnames = { # run buildskinname to check what these should be
    # 2024-07-02
    'aierdeliqi_8': 'EldridgeSchool2',
    'guanghui_7': 'IllustriousWork',
    'u31_2': 'U-31School',
    'u31': 'U-31',
    'yaerweite_2': 'AlvitrWork',
    'yaerweite': 'Alvitr',
    'yuekegongjue_4': 'Duke of YorkWork',
    'z43_2': 'Z43School',
    'z43': 'Z43',
    'z47_2': 'Z47School',
    'z47': 'Z47',
    # 2024-07-11
    'aijier_3': 'ÄgirSpring',
    'aersasi': 'Alsace',
    'beiyade': 'Bayard',
    'dashan': 'Daisen',
    'haerfude': 'Halford',
    'haitian_5': 'Hai TienSpring2',
    'nabulesi': 'Napoli',
    'naximofu': 'Admiral Nakhimov',
    # 2024-07-25
    'dipulaikesi': 'Dupleix',
    'dipulaikesi_2': 'DupleixRaceQueen',
    'guogan': 'L\'Audacieux',
    'guogan_2': 'L\'AudacieuxRaceQueen',
    'haman_6': 'HammannRaceQueen',
    'luoma_4': 'RomaSummer',
    'ruihe_4': 'ZuikakuRaceQueen2',
    'sitelasibao': 'Strasbourg',
    'sitelasibao_2': 'StrasbourgRaceQueen',
    'u96_4': 'U-96RaceQueen',
    'xiafei_4': 'JoffreRaceQueen',
    'xia_alter': 'Kasumi META',
    # 2024-08-15
    'aierdeliqi_g': 'EldridgeKai',
    'ankeleiqi_h': 'AnchorageWedding',
    'banerwei_3': 'PainlevéSummer',
    'beier_2': 'BellWild West',
    'beier': 'Bell',
    'dujiaoshou_11': 'UnicornSport',
    'fage_2': 'FargoWild West',
    'fage': 'Fargo',
    'feiteliedadi_2': 'Friedrich der GroßeNew Year',
    'feiteliedadi_3': 'Friedrich der GroßeSummer',
    'feiteliedadi_h': 'Friedrich der GroßeWedding',
    'feiteliedadi': 'Friedrich der Große',
    'feiyu_2': 'HerringWild West',
    'feiyu': 'Herring',
    'kaiersheng_3': 'KersaintWild West',
    'pizibao_2': 'PittsburghWild West',
    'pizibao': 'Pittsburgh',
    'u556_2': 'U-556Party',
    'u556_3': 'U-556Wild West',
    'u556': 'U-556',
    'yindianna_2': 'IndianaWild West',
    'yindianna': 'Indiana',
    # 2024-08-29
    'lingbo_10': 'AyanamiParty',
    'ruifeng': 'Zuihou',
    'ruifeng_2': 'ZuihouTheme Park',
    # 2024-09-05
    'changmen_alter': 'Nagato META',
    'huangjiafangzhou_6': 'Ark RoyalTheme Park',
    'muyue_5': 'MutsukiTheme Park',
    'yuekecheng_alter': 'Yorktown META',
    # 2024-09-12
    'beierfasite_9': 'BelfastTheme Park',
    'birui_alter': 'Hiei META',
    'chicheng_alter': 'Akagi META',
    'chuixue_7': 'FubukiSpring',
    'dulianglai_2': 'WataraseParty',
    'dulianglai': 'Watarase',
    # 'huangjianfangzhou_6': 'Ark RoyalTheme Park', # typo dupe of huangjiafangzhou_6
    'liangbo_2': 'SuzunamiTheme Park',
    'liangbo': 'Suzunami',
    'linglai_2': 'AyaseHome Relaxation',
    'linglai': 'Ayase',
    'malilan_g': 'MarylandKai',
    'tiancheng_cv_2': 'Amagi(CV)Party',
    'tiancheng_cv': 'Amagi(CV)',
    'xiefeierde_6': 'SheffieldTheme Park',
    'z35_4': 'Z35Theme Park',
    # 2024-09-19
    'dingan_3': 'Ting AnTheme Park',
    'geluosite_2': 'GloucesterSpring',
    'geluosite_3': 'GloucesterTheme Park',
    'longxiang_4': 'RyuujouTheme Park',
    'lupuleixite_3': 'Prinz RupprechtTheme Park',
    'tianlangxing': 'Sirius',
    'tianlangxing_5': 'SiriusTheme Park',
    'wuzang_3': 'MusashiTheme Park',
    'bulaimodun_6': 'BremertonTheme Park',
    'jianye_5': 'KashinoTheme Park',
    # 2024-09-26 (3D Dorm Update)
    'xianghe_h': 'ShoukakuWedding',
    'xufulun_3': 'SuffrenParty',
    'bisimai_h': 'BismarckWedding',
    'fengxiang_alter': 'Houshou META',
    'fusang_h': 'FusouWedding',
    'bailong_4': 'HakuryuuFestival',
    'qiye_6': 'EnterpriseParty',
    # 2024-10-24 (tempesta/halloween)
    'aidang_6': 'AtagoHalloween',
    'bulisituoer_3': 'BristolHalloween',
    'gangyishawa': 'Ganj-i-Sawai',
    'gangyishawa_2': 'Ganj-i-SawaiHalloween',
    'gaoxiong_6': 'TakaoNinja',
    'haitunhao': 'Dolphin',
    'haitunhao_2': 'DolphinHalloween',
    'hemuhao': 'Amity',
    'hemuhao_2': 'AmityHalloween',
    'huanxianghao': 'Fancy',
    'huanxianghao_2': 'FancyHalloween',
    'pucimaosi': 'Portsmouth Adventure',
    'pucimaosi_2': 'Portsmouth AdventureHalloween',
    'weizhang_3': 'OwariHalloween',
    # 2024-11-21 (To LOVE-Ru)
    'aersasi_2': 'AlsaceSummer',
    'aogusite_3': 'August von ParsevalHome Relaxation',
    'bisimaiz_2': 'Bismarck ZweiSummer',
    'bulaimodun_3': 'BremertonSport',
    'dingan_2': 'Ting AnSpring',
    'kaisa_alter': 'Giulio Cesare META',
    'luodeni_alter': 'Rodney META',
    'weixi_5': 'WeserMaid',
    'wuerlixi_4': 'Ulrich von HuttenSchool',
    'lala_tolove': 'Lala Satalin Deviluke',
    'lala_2_tolove': 'Lala Satalin DevilukeHome Relaxation',
    'nana_tolove': 'Nana Astar Deviluke',
    'nana_2_tolove': 'Nana Astar DevilukeHome Relaxation',
    'mengmeng_tolove': 'Momo Belia Deviluke',
    'mengmeng_2_tolove': 'Momo Belia DevilukeHome Relaxation',
    'jinseanying_tolove': 'Golden Darkness',
    'jinseanying_2_tolove': 'Golden DarknessHome Relaxation',
    'xiliansi_tolove': 'Haruna Sairenji',
    'xiliansi_2_tolove': 'Haruna SairenjiHome Relaxation',
    'gushouchuan_tolove': 'Yui Kotegawa',
    'gushouchuan_2_tolove': 'Yui KotegawaHome Relaxation',
    # 2024-12-12
    'bulvxieer_2': 'BlücherSport',
    'dafeng_alter': 'Taihou META',
    'lafeiii_3': 'Laffey IIBunny',
    'madamm': 'Madam M',
    'moon': 'Arbiter: The Moon XVIII',
    'xingzuo_2': 'ConstellationBunny',
    'xipeierhaijunshangjiang_alter': 'Admiral Hipper META',
    'yade_2': 'JadeSummer',
    # 2024-12-19 (Substellar)
    'z52_2': 'Z52Bunny',
    'z52': 'Z52',
    'aijier_4': 'ÄgirHome Relaxation',
    'bisimai_4': 'BismarckChristmas',
    'duyisibao_2': 'DuisburgBunny',
    'duyisibao': 'Duisburg',
    'fulici_2': 'Fritz RumeyBunny',
    'fulici': 'Fritz Rumey',
    'kewei_5': 'FormidableBunny',
    'yanusi_6': 'JanusBunny',
    'z9_2': 'Z9Bunny',
    'z9': 'Z9',
    'z11_2': 'Z11Bunny',
    'z11': 'Z11',
    # 2024-12-26 (Substellar Part 2)
    'beiyade_2': 'BayardBunny',
    'dashan_2': 'DaisenBunny',
    'haerfude_2': 'HalfordBunny',
    'leigensibao_3': 'RegensburgBunny',
    'nabulesi_2': 'NapoliBunny',
    'naximofu_2': 'Admiral NakhimovBunny',
    'xinnong_5': 'ShinanoBunny',
    'zhumo_2': 'ChikumaBunny',
    # 2025-01-09 (Superimposition Rerun)
    'daofeng_6': 'ShimakazeSpring',
    'xinnong_4': 'ShinanoSummer',
    'zhenhai_3': 'Chen HaiParty',
    # 2025-01-16 (Lunar New Year)
    'changfeng_2': 'Chang FengSpring',
    'changfeng': 'Chang Feng',
    'changmen_6': 'NagatoSpring',
    'fubo': 'Fu Po',
    'fubo_2': 'Fu PoSpring',
    'fushun_g': 'Fu ShunKai',
    'hairong': 'Hai Yung',
    'hairong_2': 'Hai YungSpring',
    'huajia_g': 'Hwah JahKai',
    'jianwu': 'Chien Wu',
    'jianwu_2': 'Chien WuSpring',
    'jianwu_3': 'Chien WuSpringForm2',
    'qiershazhi_3': 'KearsargeSpring',
    'buleisite_3': 'BrestSpring',
    # 2025-01-23 (Project Identity: Oceana)
    'aersasi_2': 'AlsaceSummer',
    'bailu_3': 'ShiratsuyuSpring',
    'boerzhanuo_alter': 'Bolzano META',
    'diliyasite_4': 'TriesteSpring',
    'fanji': 'Repulse',
    'fanji_3': 'RepulseTravel',
    'meiyinci_3': 'MainzSpring',
    'moermansike_3': 'MurmanskSpring',
    'rangbaer_5': 'Jean BartSpring',
    'shengnvzhende': 'Jeanne d\'Arc',
    'shengnvzhende_2': 'Jeanne d\'ArcSummer',
    'shengnvzhende_3': 'Jeanne d\'ArcSpring',
    'xinzexi_4': 'New JerseySpring',
    'lingyangzhe1_1': 'NaviBaby',
    'lingyangzhe1_2': 'NaviBabySchool',
    'lingyangzhe21_1': 'NaviMildTeen',
    'lingyangzhe22_1': 'NaviRebelliousTeen',
    'lingyangzhe22_2': 'NaviTeen',
    'lingyangzhe31_1': 'NaviMild',
    'lingyangzhe31_2': 'NaviMildCasual',
    'lingyangzhe32_1': 'NaviRebellious',
    'lingyangzhe32_2': 'NaviRebelliousCasual',
    'lingyangzhe32_3': 'Navi',
    'lingyangzhe3_2': 'NaviHome Relaxation',
    'npclingyangzhe3_2': 'NaviHome RelaxationWithoutBG',
    # 2025-02-13 (Valentine's)
    'changbo_5': 'NaganamiCasual',
    'nubiyaren': 'Nubian',
    'nubiyaren_2': 'NubianRPG',
    'nubiyaren_3': 'NubianMaid',
    # 2025-02-20
    'anshan_3': 'An ShanSchool',
    'longwu_2': 'Lung WuSpring',
    'npcandelieyaduoliya_alter': 'NPCAndrea Doria META',
    'youtuobiya': 'Eutopia Savoy',
    # 2025-02-27 (A Day After Kizuna AI Returned)
    'balaka': 'Maggiore Baracca',
    'balaka_2': 'Maggiore BaraccaNile Colors',
    'batuoluomeiao': 'Bartolomeo Colleoni',
    'batuoluomeiao_2': 'Bartolomeo ColleoniNile Colors',
    'chariot': 'Arbiter: The Chariot VII',
    'jian_3': 'Chi AnNile Colors',
    'jiaosuai': 'Giosuè Carducci',
    'jiaosuai_2': 'Giosuè CarducciNile Colors',
    'lafeier': 'Raffaello',
    'lafeier_2': 'RaffaelloNile Colors',
    'lianren': 'War Protocol Scythe',
    'missr': 'Bon Homme Richard',
    'shenpanjizhanche': 'MECHArbiter: The Chariot',
    'sikula_4': 'ScyllaNile Colors',
    'yulun': 'War Protocol Moon',
    'andelieyaduoliya_alter': 'Andrea Doria META',
    # 2025-03-13
    'dahuangfeng_alter': 'Hornet META',
    # 2025-03-20 (Virtual Tower Rerun)
    'dafeng_6': 'TaihouSummer',
    'haifeng_3': 'UmikazeSchool',
    'siwanshi_2': 'ShimantoMaid',
    # 2025-03-27 (Valley Hospital)
    'fulankelin': 'Franklin',
    'fulankelin_2': 'FranklinHospital',
    'fuluoxiluofu_3': 'VoroshilovHospital',
    'huashengdun': 'Washington',
    'huashengdun_3': 'WashingtonHospital',
    'linggu_3': 'SuzuyaHospital',
    'mile': 'Miller',
    'mile_2': 'MillerHospital',
    'mojiaduoer_3': 'MogadorHospital',
    'neihuada_alter': 'Nevada META',
    'shengtafei': 'Santa Fe',
    'shengtafei_2': 'Santa FeHospital',
    'shensu_4': 'StremitelnyTravel',
    # 2025-04-01 (April Fools)
    'buli_super_2': 'Specialized Bulin Custom MKIIIEvent',
    # 2025-04-10
    'quejie': 'Swiftsure',
    # 2025-04-17
    'dujiaoshou_10': 'UnicornRPG',
    'feiteliekaer_2': 'Friedrich CarlHome Relaxation',
    'yuanchou_2': 'ImplacableSchool',
    # 2025-04-24 (Tulipa)
    'aerbien_4': 'AlbionHome Relaxation',
    'aifosen': 'Evertsen',
    'aifosen_2': 'EvertsenHome Relaxation',
    'ankeleiqi_younv': 'Little Anchorage',
    'aoliege': 'Oleg',
    'aoliege_2': 'OlegHome Relaxation',
    'bailong_5': 'HakuryuuHome Relaxation',
    'kashan': 'Kazan',
    'kashan_2': 'KazanHome Relaxation',
    'qisheng': 'De Zeven Provinciën',
    'qisheng_2': 'De Zeven ProvinciënHome Relaxation',
    'taiyuan_3': 'Tai YuanHome Relaxation',
    # 2025-05-14 (Wednesday Update)
    'aierbin_3': 'ElbingHome Relaxation',
    'enpuleisi': 'Lady E',
    'npcgelunweier_alter': 'Grenville META',
    'npcguangrong_alter': 'NPCGlorious META',
    'shuixingjinian_6': 'Pamiat\' MerkuriaEvent',
    'weineituo_2': 'Vittorio VenetoSummer',
    'z23_12': 'Z23Party2',
    # 2025-05-20 (Tuesday Update)
    'dafeng_7': 'TaihouBunny',
    'guanghui_8': 'IllustriousCasual',
    'guangrong_alter': 'Glorious META',
    'keliaopeitela': 'Cleopatra',
    'keliaopeitela_2': 'CleopatraSummer',
    'magician': 'Arbiter: The Magician I',
    'npcchuyue_3': 'Hatsuzuki_SKIN3',
    'npcfeiteliekaer_3': 'Friedrich Carl_SKIN3',
    'npcheianjie_alter': 'Erebus META',
    'npcjunzhu_5': 'Monarch_SKIN5',
    'npckewei_6': 'Formidable_SKIN6',
    'npclieren_alter': 'Hunter META',
    'npcmalilan_3': 'Maryland_SKIN3',
    'shi': 'Lion',
    'shi_2': 'LionSummer',
    'siwanshi_3': 'ShimantoSummer',
    'siwanshi_4': 'ShimantoSummerForm2',
    'star': 'Star',
    'telafaerjia': 'Trafalgar',
    'telafaerjia_2': 'TrafalgarSummer',
    'telinida': 'Trinidad',
    'telinida_2': 'TrinidadSummer',
    'yinghuochong_g': 'GlowwormKai',
    'yongqi': 'Gallant',
    'yongqi_2': 'GallantHome Relaxation',
    'unknownstar': 'Arbiter: The Star XVII',
}

dupes = set()
for id in shipnames:
    shipnames[id] = re.sub(r'[<>:"/\\|?*]+', '', shipnames[id])
    shipname = shipnames[id]
    if shipname in dupes:
        print('WARNING: Duplicate ship name: {}'.format(shipname))
    dupes.add(shipname)
