shipnames = { # run buildskinname to check what these should be
    # 2024-07-02
    'aierdeliqi_8': 'EldridgeSchool2',
    'guanghui_7': 'IllustriousWork',
    'u31_2': 'U-31School',
    'u31': 'U-31',
    'yaerweite_2': 'AlvitrWork',
    'yaerweite': 'Alvitr',
    'yuekegongjue_4': 'Duke of YorkWork',
    'z43_2': 'Z43School',
    'z43': 'Z43',
    'z47_2': 'Z47School',
    'z47': 'Z47',
    # 2024-07-11
    'aijier_3': 'ÄgirSpring',
    'aersasi': 'Alsace',
    'beiyade': 'Bayard',
    'dashan': 'Daisen',
    'haerfude': 'Halford',
    'haitian_5': 'Hai TienSpring2',
    'nabulesi': 'Napoli',
    'naximofu': 'Admiral Nakhimov',
    # 2024-07-25
    'dipulaikesi': 'Dupleix',
    'dipulaikesi_2': 'DupleixRaceQueen',
    'guogan': 'L\'Audacieux',
    'guogan_2': 'L\'AudacieuxRaceQueen',
    'haman_6': 'HammannRaceQueen',
    'luoma_4': 'RomaSummer',
    'ruihe_4': 'ZuikakuRaceQueen2',
    'sitelasibao': 'Strasbourg',
    'sitelasibao_2': 'StrasbourgRaceQueen',
    'u96_4': 'U-96RaceQueen',
    'xiafei_4': 'JoffreRaceQueen',
    'xia_alter': 'Kasumi META',
    # 2024-08-15
    'aierdeliqi_g': 'EldridgeKai',
    'ankeleiqi_h': 'AnchorageWedding',
    'banerwei_3': 'PainlevéSummer',
    'beier_2': 'BellWild West',
    'beier': 'Bell',
    'dujiaoshou_11': 'UnicornSport',
    'fage_2': 'FargoWild West',
    'fage': 'Fargo',
    'feiteliedadi_2': 'Friedrich der GroßeNew Year',
    'feiteliedadi_3': 'Friedrich der GroßeSummer',
    'feiteliedadi_h': 'Friedrich der GroßeWedding',
    'feiteliedadi': 'Friedrich der Große',
    'feiyu_2': 'HerringWild West',
    'feiyu': 'Herring',
    'kaiersheng_3': 'KersaintWild West',
    'pizibao_2': 'PittsburghWild West',
    'pizibao': 'Pittsburgh',
    'u556_2': 'U-556Party',
    'u556_3': 'U-556Wild West',
    'u556': 'U-556',
    'yindianna_2': 'IndianaWild West',
    'yindianna': 'Indiana',
    # 2024-08-29
    'lingbo_10': 'AyanamiParty',
    'ruifeng': 'Zuihou',
    'ruifeng_2': 'ZuihouTheme Park',
    # 2024-09-05
    'changmen_alter': 'Nagato META',
    'huangjiafangzhou_6': 'Ark RoyalTheme Park',
    'muyue_5': 'MutsukiTheme Park',
    'yuekecheng_alter': 'Yorktown META',
    # 2024-09-12
    'beierfasite_9': 'BelfastTheme Park',
    'birui_alter': 'Hiei META',
    'chicheng_alter': 'Akagi META',
    'chuixue_7': 'FubukiSpring',
    'dulianglai_2': 'WataraseParty',
    'dulianglai': 'Watarase',
    'huangjianfangzhou_6': 'Ark RoyalTheme Park', # dupe of huangjiafangzhou_6
    'liangbo_2': 'SuzunamiTheme Park',
    'liangbo': 'Suzunami',
    'linglai_2': 'AyaseHome Relaxation',
    'linglai': 'Ayase',
    'malilan_g': 'MarylandKai',
    'tiancheng_cv_2': 'Amagi(CV)Party',
    'tiancheng_cv': 'Amagi(CV)',
    'xiefeierde_6': 'SheffieldTheme Park',
    'z35_4': 'Z35Theme Park',
    # 2024-09-19
    'dingan_3': 'Ting AnTheme Park',
    'geluosite_2': 'GloucesterSpring',
    'geluosite_3': 'GloucesterTheme Park',
    'longxiang_4': 'RyuujouTheme Park',
    'lupuleixite_3': 'Prinz RupprechtTheme Park',
    'tianlangxing': 'Sirius',
    'tianlangxing_5': 'SiriusTheme Park',
    'wuzang_3': 'MusashiTheme Park',
    'bulaimodun_6': 'BremertonTheme Park',
    'jianye_5': 'KashinoTheme Park',
    # 2024-09-26 (3D Dorm Update)
    'xianghe_h': 'ShoukakuWedding',
    'xufulun_3': 'SuffrenParty',
    'bisimai_h': 'BismarckWedding',
    'fengxiang_alter': 'Houshou META',
    'fusang_h': 'FusouWedding',
    'bailong_4': 'HakuryuuFestival',
    'qiye_6': 'EnterpriseParty',
    # 2024-10-24 (tempesta/halloween)
    'aidang_6': 'AtagoHalloween',
    'bulisituoer_3': 'BristolHalloween',
    'gangyishawa': 'Ganj-i-Sawai',
    'gangyishawa_2': 'Ganj-i-SawaiHalloween',
    'gaoxiong_6': 'TakaoNinja',
    'haitunhao': 'Dolphin',
    'haitunhao_2': 'DolphinHalloween',
    'hemuhao': 'Amity',
    'hemuhao_2': 'AmityHalloween',
    'huanxianghao': 'Fancy',
    'huanxianghao_2': 'FancyHalloween',
    'pucimaosi': 'Portsmouth Adventure',
    'pucimaosi_2': 'Portsmouth AdventureHalloween',
    'weizhang_3': 'OwariHalloween',
    # 2024-11-21 (To LOVE-Ru)
    'aersasi_2': 'AlsaceSummer',
    'aogusite_3': 'August von ParsevalHome Relaxation',
    'bisimaiz_2': 'Bismarck ZweiSummer',
    'bulaimodun_3': 'BremertonSport',
    'dingan_2': 'Ting AnSpring',
    'kaisa_alter': 'Giulio Cesare META',
    'luodeni_alter': 'Rodney META',
    'weixi_5': 'WeserMaid',
    'wuerlixi_4': 'Ulrich von HuttenSchool',
    'lala_tolove': 'Lala Satalin Deviluke',
    'lala_2_tolove': 'Lala Satalin DevilukeHome Relaxation',
    'nana_tolove': 'Nana Astar Deviluke',
    'nana_2_tolove': 'Nana Astar DevilukeHome Relaxation',
    'mengmeng_tolove': 'Momo Belia Deviluke',
    'mengmeng_2_tolove': 'Momo Belia DevilukeHome Relaxation',
    'jinseanying_tolove': 'Golden Darkness',
    'jinseanying_2_tolove': 'Golden DarknessHome Relaxation',
    'xiliansi_tolove': 'Haruna Sairenji',
    'xiliansi_2_tolove': 'Haruna SairenjiHome Relaxation',
    'gushouchuan_tolove': 'Yui Kotegawa',
    'gushouchuan_2_tolove': 'Yui KotegawaHome Relaxation',
    # 2024-12-12
    'bulvxieer_2': 'BlücherSport',
    'dafeng_alter': 'Taihou META',
    'lafeiii_3': 'Laffey IIBunny',
    'madamm': 'Madam M',
    'moon': 'Arbiter The Moon XVIII',
    'xingzuo_2': 'ConstellationBunny',
    'xipeierhaijunshangjiang_alter': 'Admiral Hipper META',
    'yade_2': 'JadeSummer',
    # 2024-12-19 (Substellar)
    'z52_2': 'Z52Bunny',
    'z52': 'Z52',
    'aijier_4': 'ÄgirHome Relaxation',
    'bisimai_4': 'BismarckChristmas',
    'duyisibao_2': 'DuisburgBunny',
    'duyisibao': 'Duisburg',
    'fulici_2': 'Fritz RumeyBunny',
    'fulici': 'Fritz Rumey',
    'kewei_5': 'FormidableBunny',
    'yanusi_6': 'JanusBunny',
    'z9_2': 'Z9Bunny',
    'z9': 'Z9',
    'z11_2': 'Z11Bunny',
    'z11': 'Z11',
    # 2024-12-26 (Substellar Part 2)
    'beiyade_2': 'BayardBunny',
    'dashan_2': 'DaisenBunny',
    'haerfude_2': 'HalfordBunny',
    'leigensibao_3': 'RegensburgBunny',
    'nabulesi_2': 'NapoliBunny',
    'naximofu_2': 'Admiral NakhimovBunny',
    'xinnong_5': 'ShinanoBunny',
    'zhumo_2': 'ChikumaBunny',
    # 2025-01-09 (Superimposition Rerun)
    'daofeng_6': 'ShimakazeSpring',
    'xinnong_4': 'ShinanoSummer',
    'zhenhai_3': 'Chen HaiParty',
    # 2025-01-16 (Lunar New Year)
    'changfeng_2': 'Chang FengSpring',
    'changfeng': 'Chang Feng',
    'changmen_6': 'NagatoSpring',
    'fubo': 'Fu Po',
    'fubo_2': 'Fu PoSpring',
    'fushun_g': 'Fu ShunKai',
    'hairong': 'Hai Yung',
    'hairong_2': 'Hai YungSpring',
    'huajia_g': 'Hwah JahKai',
    'jianwu': 'Chien Wu',
    'jianwu_2': 'Chien WuSpring',
    'jianwu_3': 'Chien WuSpringForm2',
    'qiershazhi_3': 'KearsargeSpring',
    'buleisite_3': 'BrestSpring',
}
