import re
import json
from time import sleep
from urllib.request import urlopen
from urllib.parse import quote

year = 25

try:
    with open('one-offs/valentine20{}_wikitext.json'.format(year), 'r') as fp:
        letters = json.load(fp)
except Exception as e:
    # update letters every year; run the following javascript on https://azurlane.koumakan.jp/wiki/List_of_Ships
    # Array.from(document.querySelectorAll("table")).filter((t, i) => i < 3).map(t => Array.from(t.rows).filter((r, j) => j > 0)).flat().map(r => r.cells[1].textContent);
    # check for \n in results; replace with <br>
    letters = {
        'Universal Bulin': '',
        'Prototype Bulin MKII': '',
        'Specialized Bulin Custom MKIII': '',
        'Dewey': '',
        'Cassin': '',
        'Downes': '',
        'Gridley': '',
        'Craven': '',
        'McCall': '',
        'Maury': '',
        'Fletcher': '',
        'Charles Ausburne': '',
        'Thatcher': '',
        'Aulick': '',
        'Foote': '',
        'Spence': '',
        'Benson': '',
        'Laffey': '',
        'Sims': '',
        'Hammann': '',
        'Eldridge': '',
        'Omaha': '',
        'Raleigh': '',
        'Brooklyn': '',
        'Phoenix': '',
        'Helena': '',
        'Atlanta': '',
        'Juneau': '',
        'San Diego': '',
        'Cleveland': '',
        'Columbia': '',
        'Pensacola': '',
        'Salt Lake City': '',
        'Northampton': '',
        'Chicago': '',
        'Houston': '',
        'Portland': '',
        'Indianapolis': '',
        'Astoria': '',
        'Quincy': '',
        'Vincennes': '',
        'Wichita': '',
        'Baltimore': '',
        'Nevada': '',
        'Oklahoma': '',
        'Pennsylvania': '',
        'Arizona': '',
        'Tennessee': '',
        'California': '',
        'Colorado': '',
        'Maryland': '',
        'West Virginia': '',
        'North Carolina': '',
        'Washington': '',
        'South Dakota': '',
        'Indiana': '',
        'New Jersey': '',
        'Long Island': '',
        'Bogue': '',
        'Langley': '',
        'Lexington': '',
        'Saratoga': '',
        'Ranger': '',
        'Yorktown': '',
        'Enterprise': '',
        'Hornet': '',
        'Wasp': '',
        'Vestal': '',
        'Amazon': '',
        'Acasta': '',
        'Ardent': '',
        'Beagle': '',
        'Bulldog': '',
        'Comet': '',
        'Crescent': '',
        'Cygnet': '',
        'Foxhound': '',
        'Fortune': '',
        'Grenville': '',
        'Glowworm': '',
        'Hardy': '',
        'Hunter': '',
        'Javelin': '',
        'Juno': '',
        'Vampire': '',
        'Leander': '',
        'Achilles': '',
        'Ajax': '',
        'Dido': '',
        'Southampton': '',
        'Sheffield': '',
        'Manchester': '',
        'Gloucester': '',
        'Edinburgh': '',
        'Belfast': '',
        'Arethusa': '',
        'Galatea': '',
        'Aurora': '',
        'London': '',
        'Shropshire': '',
        'Kent': '',
        'Suffolk': '',
        'Norfolk': '',
        'Dorsetshire': '',
        'York': '',
        'Exeter': '',
        'Renown': '',
        'Repulse': '',
        'Hood': '',
        'Queen Elizabeth': '',
        'Warspite': '',
        'Nelson': '',
        'Rodney': '',
        'King George V': '',
        'Prince of Wales': '',
        'Duke of York': '',
        'Vanguard': '',
        'Hermes': '',
        'Unicorn': '',
        'Eagle': '',
        'Ark Royal': '',
        'Illustrious': '',
        'Victorious': '',
        'Formidable': '',
        'Glorious': '',
        'Erebus': '',
        'Terror': '',
        'Fubuki': '',
        'Shirayuki': '',
        'Miyuki': '',
        'Ayanami': '',
        'Akatsuki': '',
        'Hibiki': '',
        'Ikazuchi': '',
        'Inazuma': '',
        'Shiratsuyu': '',
        'Yuudachi': '',
        'Shigure': '',
        'Yukikaze': '',
        'Kagerou': '',
        'Shiranui': '',
        'Nowaki': '',
        'Hatsuharu': '',
        'Wakaba': '',
        'Hatsushimo': '',
        'Ariake': '',
        'Yuugure': '',
        'Kuroshio': '',
        'Oyashio': '',
        'Yuubari': '',
        'Nagara': '',
        'Isuzu': '',
        'Natori': '',
        'Yura': '',
        'Kinu': '',
        'Abukuma': '',
        'Mogami': '',
        'Mikuma': '',
        'Furutaka': '',
        'Kako': '',
        'Aoba': '',
        'Kinugasa': '',
        'Chikuma': '',
        'Myoukou': '',
        'Nachi': '',
        'Ashigara': '',
        'Haguro': '',
        'Takao': '',
        'Atago': '',
        'Maya': '',
        'Choukai': '',
        'Kongou': '',
        'Hiei': '',
        'Haruna': '',
        'Kirishima': '',
        'Fusou': '',
        'Yamashiro': '',
        'Ise': '',
        'Hyuuga': '',
        'Nagato': '',
        'Mutsu': '',
        'Kii': '',
        'Tosa': '',
        'Musashi': '',
        'Hiyou': '',
        'Junyou': '',
        'Houshou': '',
        'Zuihou': '',
        'Shouhou': '',
        'Ryuujou': '',
        'Akagi': '',
        'Kaga': '',
        'Souryuu': '',
        'Hiryuu': '',
        'Shoukaku': '',
        'Zuikaku': '',
        'Taihou': '',
        'Shinano': '',
        'Akashi': '',
        'Z1': '',
        'Z23': '',
        'Z25': '',
        'Königsberg': '',
        'Karlsruhe': '',
        'Köln': '',
        'Leipzig': '',
        'Admiral Hipper': '',
        'Blücher': '',
        'Prinz Eugen': '',
        'Deutschland': '',
        'Admiral Graf Spee': '',
        'Scharnhorst': '',
        'Gneisenau': '',
        'Bismarck': '',
        'Tirpitz': '',
        'Graf Zeppelin': '',
        'An Shan': '',
        'Fu Shun': '',
        'Chang Chun': '',
        'Tai Yuan': '',
        'Yat Sen': '',
        'Ning Hai': '',
        'Ping Hai': '',
        'Avrora': '',
        'Bailey': '',
        'Z19': '',
        'Z20': '',
        'Z21': '',
        'Z46': '',
        'Shimakaze': '',
        'Kamikaze': '',
        'Matsukaze': '',
        'Mutsuki': '',
        'Kisaragi': '',
        'Uzuki': '',
        'Minazuki': '',
        'Fumizuki': '',
        'Nagatsuki': '',
        'Mikazuki': '',
        'Umikaze': '',
        'Yamakaze': '',
        'Kawakaze': '',
        'Kiyonami': '',
        'Niizuki': '',
        'Harutsuki': '',
        'Yoizuki': '',
        'Radford': '',
        'Jenkins': '',
        'Nicholas': '',
        'Richmond': '',
        'Honolulu': '',
        'St. Louis': '',
        'Jupiter': '',
        'Jersey': '',
        'Sendai': '',
        'Jintsuu': '',
        'Naka': '',
        'Urakaze': '',
        'Isokaze': '',
        'Hamakaze': '',
        'Tanikaze': '',
        'Mikasa': '',
        'Agano': '',
        'Noshiro': '',
        'Sakawa': '',
        'Matchless': '',
        'Musketeer': '',
        'Fiji': '',
        'Jamaica': '',
        'Montpelier': '',
        'Denver': '',
        'Asashio': '',
        'Ooshio': '',
        'Michishio': '',
        'Arashio': '',
        'Little Bel': '',
        'Abercrombie': '',
        'Sussex': '',
        'I-19': '',
        'I-26': '',
        'I-58': '',
        'U-81': '',
        'Dace': '',
        'U-47': '',
        'U-557': '',
        'Z35': '',
        'Z18': '',
        'Le Triomphant': '',
        'Forbin': '',
        'Émile Bertin': '',
        'Surcouf': '',
        'Le Mars': '',
        'Dunkerque': '',
        'Jean Bart': '',
        'Massachusetts': '',
        'Bush': '',
        'Centaur': '',
        'Essex': '',
        'Albacore': '',
        'Le Téméraire': '',
        'Memphis': '',
        'Newcastle': '',
        'Hobby': '',
        'Kalk': '',
        'Minneapolis': '',
        'Hazelwood': '',
        'Concord': '',
        'Amagi': '',
        'Kaga (Battleship)': '',
        'Hatakaze': '',
        'Makinami': '',
        'Sirius': '',
        'Curacoa': '',
        'Curlew': '',
        'Kimberly': '',
        'Mullany': '',
        'Chaser': '',
        'Independence': '',
        'Shangri-La': '',
        'Z2': '',
        'Bunker Hill': '',
        'I-13': '',
        'Suzuya': '',
        'Hiei-chan': '',
        'Akagi-chan': '',
        'Zeppy': '',
        'U-556': '',
        'U-73': '',
        'Z36': '',
        'Echo': '',
        'Lena': '',
        'Clevelad': '',
        'Li\'l Sandy': '',
        'Swiftsure': '',
        'Le Malin': '',
        'L\'Opiniâtre': '',
        'I-25': '',
        'I-56': '',
        'I-168': '',
        'U-101': '',
        'U-522': '',
        'Alabama': '',
        'Cavalla': '',
        'Bataan': '',
        'San Juan': '',
        'Birmingham': '',
        'Aylwin': '',
        'Bache': '',
        'Black Prince': '',
        'Stanly': '',
        'Littorio': '',
        'Conte di Cavour': '',
        'Giulio Cesare': '',
        'Zara': '',
        'Trento': '',
        'Carabiniere': '',
        'U-110': '',
        'Smalley': '',
        'Gascogne µ': '',
        'Akagi µ': '',
        'Cleveland µ': '',
        'Sheffield µ': '',
        'Admiral Hipper µ': '',
        'Glasgow': '',
        'Kasumi': '',
        'Suruga': '',
        'Ryuuhou': '',
        'Halsey Powell': '',
        'Biloxi': '',
        'Uranami': '',
        'Grozny': '',
        'Minsk': '',
        'Tashkent': '',
        'Pamiat\' Merkuria': '',
        'Kirov': '',
        'Chapayev': '',
        'Gangut': '',
        'Sovetsky Soyuz': '',
        'Sovetskaya Belorussiya': '',
        'Sovetskaya Rossiya': '',
        'Intrepid': '',
        'Bremerton': '',
        'Cooper': '',
        'Reno': '',
        'Bluegill': '',
        'Casablanca': '',
        'Marblehead': '',
        'Hanazuki': '',
        'Naganami': '',
        'Little Renown': '',
        'Tartu': '',
        'Richelieu': '',
        'Jeanne d\'Arc': '',
        'Algérie': '',
        'La Galissonnière': '',
        'Vauquelin': '',
        'Béarn': '',
        'Little Illustrious': '',
        'Eskimo': '',
        'Howe': '',
        'Perseus': '',
        'Hermione': '',
        'Valiant': '',
        'Icarus': '',
        'Z26': '',
        'U-96': '',
        'Suzutsuki': '',
        'Kumano': '',
        'Chitose': '',
        'Chiyoda': '',
        'Kashino': '',
        'Princeton': '',
        'Taihou µ': '',
        'Tashkent µ': '',
        'Dido µ': '',
        'Albacore µ': '',
        'Baltimore µ': '',
        'Roon µ': '',
        'Illustrious µ': '',
        'Le Malin µ': '',
        'Peter Strasser': '',
        'Prinz Heinrich': '',
        'U-37': '',
        'Weser': '',
        'Nürnberg': '',
        'Z24': '',
        'Z28': '',
        'Pola': '',
        'Vincenzo Gioberti': '',
        'Stremitelny': '',
        'U-410': '',
        'Ying Swei': '',
        'Chao Ho': '',
        'Penelope': '',
        'Tallinn': '',
        'Gremyashchy': '',
        'Murmansk': '',
        'Gromky': '',
        'Vittorio Veneto': '',
        'Duca degli Abruzzi': '',
        'Aquila': '',
        'Torricelli': '',
        'Maestrale': '',
        'Libeccio': '',
        'Nicoloso da Recco': '',
        'Oite': '',
        'Allen M. Sumner': '',
        'Stephen Potter': '',
        'Amagi-chan': '',
        'Ticonderoga': '',
        'San Francisco': '',
        'Archerfish': '',
        'Boise': '',
        'Morrison': '',
        'Little Enterprise': '',
        'Kazagumo': '',
        'Ingraham': '',
        'Nautilus': '',
        'Katsuragi': '',
        'New Orleans': '',
        'Le Terrible': '',
        'Maillé Brézé': '',
        'Foch': '',
        'Magdeburg': '',
        'Elbe': '',
        'Prinz Adalbert': '',
        'U-1206': '',
        'Ulrich von Hutten': '',
        'Charybdis': '',
        'Hai Tien': '',
        'Hai Chi': '',
        'Bristol': '',
        'Chen Hai': '',
        'Kiev': '',
        'Arkhangelsk': '',
        'Soobrazitelny': '',
        'Volga': '',
        'Kronshtadt': '',
        'Impero': '',
        'Pompeo Magno': '',
        'Trieste': '',
        'Seydlitz': '',
        'Lützow': '',
        'Thüringen': '',
        'Yorck': '',
        'Emden': '',
        'Elbing': '',
        'Little Prinz Eugen': '',
        'Jervis': '',
        'Bellona': '',
        'Little Cheshire': '',
        'Indomitable': '',
        'Revenge': '',
        'Joffre': '',
        'L\'Indomptable': '',
        'Enterprise (Royal Navy)': '',
        'Leonardo da Vinci': '',
        'Giuseppe Garibaldi': '',
        'Bolzano': '',
        'Roma': '',
        'Alfredo Oriani': '',
        'Emanuele Pessagno': '',
        'Z16': '',
        'Brünhilde': '',
        'Wakatsuki': '',
        'Little Spee': '',
        'Janus': '',
        'Albion': '',
        'Royal Fortune': '',
        'Hornet II': '',
        'Langley II': '',
        'Yorktown II': '',
        'Northampton II': '',
        'Hammann II': '',
        'Kuybyshev': '',
        'Theseus': '',
        'Hwah Jah': '',
        'Ting An': '',
        'Implacable': '',
        'Royal Oak': '',
        'Argus': '',
        'Scylla': '',
        'Hero': '',
        'Kursk': '',
        'Sevastopol': '',
        'Voroshilov': '',
        'Little Formidable': '',
        'Otto von Alvensleben': '',
        'Jade': '',
        'Regensburg': '',
        'Bismarck Zwei': '',
        'Taihou-chan': '',
        'Andrea Doria': '',
        'Attilio Regolo': '',
        'Gorizia': '',
        'Marseillaise': '',
        'Painlevé': '',
        'Suffren': '',
        'Kersaint': '',
        'Lyon': '',
        'Guichen': '',
        'Clemenceau': '',
        'Unzen': '',
        'Owari': '',
        'Hatsuzuki': '',
        'Asanagi': '',
        'Houston II': '',
        'Golden Hind': '',
        'Mary Celeste': '',
        'Adventure Galley': '',
        'São Martinho': '',
        'Whydah': '',
        'Laffey II': '',
        'Guam': '',
        'Constellation': '',
        'San Jacinto': '',
        'Louisville': '',
        'Flasher': '',
        'Huan Ch\'ang': '',
        'Chi An': '',
        'Lung Wu': '',
        'Hu Pen': '',
        'Fei Yuen': '',
        'Ognevoy': '',
        'Svirepy': '',
        'Poltava': '',
        'Nubian': '',
        'Liverpool': '',
        'Devonshire': '',
        'Formidable µ': '',
        'Prinz Eugen µ': '',
        'Noshiro µ': '',
        'Kongou µ': '',
        'Le Téméraire µ': '',
        'Boise µ': '',
        'Shinano-chan': '',
        'Friedrich Carl': '',
        'Alsace': '',
        'Mogador': '',
        'Brennus': '',
        'Fleuret': '',
        'Épée': '',
        'Little Friedrich': '',
        'Alvitr': '',
        'Z47': '',
        'U-31': '',
        'Z43': '',
        'Strasbourg': '',
        'L\'Audacieux': '',
        'Dupleix': '',
        'Pittsburgh': '',
        'Fargo': '',
        'Herring': '',
        'Bell': '',
        'Amagi(CV)': '',
        'Watarase': '',
        'Ayase': '',
        'Suzunami': '',
        'Ganj-i-Sawai': '',
        'Fancy': '',
        'Amity': '',
        'Portsmouth Adventure': '',
        'Dolphin': '',
        'Fritz Rumey': '',
        'Z52': '',
        'Duisburg': '',
        'Z9': '',
        'Z11': '',
        'Chien Wu': '',
        'Hai Yung': '',
        'Chang Feng': '',
        'Fu Po': '',
        'Raffaello': '',
        'Maggiore Baracca': '',
        'Giosuè Carducci': '',
        'Bartolomeo Colleoni'
        'Friedrich der Große': '',
        'Hakuryuu': '',
        'Ägir': '',
        'Plymouth': '',
        'Prinz Rupprecht': '',
        'Harbin': '',
        'Chkalov': '',
        'Brest': '',
        'Kearsarge': '',
        'Shimanto': '',
        'Felix Schultz': '',
        'Hindenburg': '',
        'Flandre': '',
        'Halford': '',
        'Daisen': '',
        'Napoli': '',
        'Admiral Nakhimov': '',
        'Bayard': '',
        'Neptune': '',
        'Monarch': '',
        'Ibuki': '',
        'Izumo': '',
        'Roon': '',
        'Saint Louis': '',
        'Seattle': '',
        'Georgia': '',
        'Kitakaze': '',
        'Azuma': '',
        'Gascogne': '',
        'Cheshire': '',
        'Drake': '',
        'Mainz': '',
        'Odin': '',
        'Champagne': '',
        'Anchorage': '',
        'August von Parseval': '',
        'Marco Polo'
        'Hiryuu META': '',
        'Ark Royal META': '',
        'Helena META': '',
        'Souryuu META': '',
        'Fusou META': '',
        'Hiyou META': '',
        'Gneisenau META': '',
        'Junyou META': '',
        'Scharnhorst META': '',
        'Yamashiro META': '',
        'Memphis META': '',
        'Repulse META': '',
        'Trento META': '',
        'Renown META': '',
        'Hunter META': '',
        'Fortune META': '',
        'Arizona META': '',
        'Sheffield META': '',
        'Queen Elizabeth META': '',
        'La Galissonnière META': '',
        'U-556 META': '',
        'Vestal META': '',
        'Algérie META': '',
        'Hatakaze META': '',
        'Jintsuu META': '',
        'Princeton META': '',
        'Erebus META': '',
        'Kirov META': '',
        'Kimberly META': '',
        'Pamiat\' Merkuria META': '',
        'Rodney META': '',
        'Vampire META': '',
        'Béarn META': '',
        'Foch META': '',
        'Wichita META': '',
        'Kasumi META': '',
        'Nagato META': '',
        'Hiei META': '',
        'Houshou META': '',
        'Giulio Cesare META': '',
        'Taihou META': '',
        'Admiral Hipper META': '',
        'Bolzano META': '',
        'Andrea Doria META': '',
        'Hornet META': ''
    }

for name in letters:
    if len(letters[name]):
        continue
    url = 'https://azurlane.koumakan.jp/w/index.php?title={}/Quotes&action=raw'.format(quote(name))
    html = urlopen(url)
    for line in html.readlines():
        if bytes('Valentine{}'.format(year), 'utf-8') in line:
            matches = re.search(b'=\s*(.+)\s*', line)
            letters[name] = matches[1].decode()
            break
    with open('one-offs/valentine20{}_wikitext.json'.format(year), 'w') as fp:
        json.dump(letters, fp, indent=4)
    sleep(1)

with open('one-offs/valentine20{}_wikitext.json'.format(year), 'w') as fp:
    json.dump(letters, fp, indent=4)
